### ISSUE TITLE
Hotkeys and Virtual Keyboard crash (Android Kitkat ?)

### ISSUE THREAD

**Issue by MajorWilly** [libretro/vice-libretro#89]
Firstly, thanks for updating this core. I noticed that the labeling has gone when changing the controls in the options but then I noticed the new Hotkeys at the bottom. Should these be hardcoded ?, because at the moment they can be changed which would then take over other keys ?

 I tried putting F11 (Toggle Virtual Keyboard) as the Start button but it crashes RetroArch.

I'm not sure if the Warp button is doing anything ? When I hold it down it just turns the sound off.

Thanks again and I hope my questions/reports are OK.

[adb log of F11 Virtual Keyboard crash.txt](https://github.com/libretro/vice-libretro/files/3446218/adb.log.of.F11.Virtual.Keyboard.crash.txt)

**Comment by paradadf** [comment]
Hi! Do you know what is the current mapping?
L = Toggle Virtual Keyboard
R = Toggle Status Bar
Hotkey = Warp mode (holding it down)

What does Select, Start, L2, R2 (maybe even L3 and R3) do now?

**Comment by MajorWilly** [comment]
When I updated the core this morning nearly all my joypad buttons are set as they were before. It says the Hotkeys are -
F11 Virtual Keyboard
F10 Status bar
RightControl Switch Joyport
End Reset
PageDown Warp

If I change my Start button (or any other button) to F11 it crashes when pressed. The other hotkeys work (not sure about warp as it seems to load the same speed).

**Comment by paradadf** [comment]
I was talking about the retropad assigned buttons.

**Comment by MajorWilly** [comment]
I'm using a GPDXD Handheld console (Android).

In the Vice Core Options it doesn't allow me to set keys to the joypad buttons. It just says -

B button (down)             B
Y button (left)                 Y
Select button                  Select
Start button                    Start
etc..

It will only let me map a joy button to a different joy button.

**Comment by MajorWilly** [comment]
I tried a different Android device with a fresh install of lr-vice. `Retropad L` is the default for virtual keyboard but it still crashes when pressing `L`.

**Comment by MajorWilly** [comment]
Any chance someone could look into this as it kind of renders this core useless to me without the virtual keyboard as I use it on a portable device with no keyboard. Otherwise i'll just have to try and go back to a version before you made these great enhancements. :(

**Comment by paradadf** [comment]
I'd suggest a little bit more patience :D

**Comment by sonninnos** [comment]
Could you also get the verbose output of RetroArch?

Yes, the warp should be significantly faster, and it might have something to do with this not skipping frames.

**Comment by sonninnos** [comment]
I don't have a device so for shit & giggles installed RA on MEmu and it surprisingly works. Even remapping the vkbd key brings it up as it should.

**Comment by MajorWilly** [comment]
@sonninnos Would it have anything to do with Android Kitkat ? My GPDXD device is Android 4.4.4 and on another device I did a clean install of lr-vice that's Android 4.4.2. Both have the crash when attempting to use the virtual keyboard. The previous version on buildbot 27th July the virtual keyboard works but it's the old virtual keyboard.

**Comment by sonninnos** [comment]
Hmm, this emulated android is 5.11, but if it did work, then there is no reason not to work anymore, because nothing major is changed in the nuklear GUI. But apparently it loses its bowels right after nuklear is summoned.

Any dice with the RetroArch log if it could be of any use?

**Comment by MajorWilly** [comment]
The RetroArch version i'm using is 1.7.6 Stable. Any version newer than that has a crashing bug on earlier Android versions that they still haven't fixed. Could this be related ? v1.7.6 Stable only has logging to the terminal which I posted an ADB log in the first post. Do you need any more ADB logs ?

**Comment by MajorWilly** [comment]
I installed the latest RetroArch Nightly on my other Android device to get a logfile.

[retroarch log Vice Virtual Keyboard crash.log](https://github.com/libretro/vice-libretro/files/3451015/retroarch.log.Vice.Virtual.Keyboard.crash.log)

**Comment by rsn8887** [comment]
Can you delete or rename your core config file?

Alternatively, go to quickmenu->options and press Start on every single option to reset it to default.

**Comment by MajorWilly** [comment]
I renamed my `retroarch-core-options.cfg` to old. This reset the core options controls to defaults (RetroPad L = RETROK_F11, RetroPad R = RETROK_F10 etc.) I also went to Core Controls and 'Deleted Core Remap', set it to Vice Joystick. Unfortunately it still crashes when trying the Virtual Keyboard button. As I say, the version on buildbot before the new virtual keyboard works fine (27th July).

**Comment by rsn8887** [comment]
Can you try Settings->Video->Threaded Video On and Off?

**Comment by MajorWilly** [comment]
I tried Threaded video On and Off, but still no joy. I also tried Vsync On and Off.

**Comment by sonninnos** [comment]
Please try updating now.

**Comment by MajorWilly** [comment]
Still crashes i'm afraid. I updated lr-vice and RetroArch to the latest Nightly. Do you need any more types of logs ?

**Comment by rsn8887** [comment]
A similar problem was fixed in Caprice32 recently. Something to do with copy surface and nuklear. https://github.com/libretro/libretro-cap32/issues/48#issuecomment-496948269

**Comment by MajorWilly** [comment]
I think that Caprice problem was for it's Hi-Res graphics mode (which I think still doesn't display in Hi-res on Android !)? 

As I say, the 27th July version of lr-vice keyboard works fine on Kitkat. I wonder if @twinaphex would be able to see the problem as he recently fixed a RetroArch quick menu crash on older Android versions.

**Comment by rsn8887** [comment]
No the hires problem was a different problem there

**Comment by rsn8887** [comment]
Can you update info files, update cores, download `Vice x64sc, accurate` core and test it? It is also C64 emulation, just more accurate, and probably doesn't crash.

**Comment by MajorWilly** [comment]
VICE x64sc doesn't crash when using the Virtual Keyboard !! So what does that mean for the regular version ?

Also, when going to the RetroArch GUI, there is no commit version hash in the bottom right corner. It just says -

1.7.7 - VICE x64 3.3 or
1.7.7 - VICE x64sc 3.3

**Comment by MajorWilly** [comment]
So do you now know the cause of this because the `sc` version keyboard works fine ? I hope it can be fixed instead of bypassing all the Android optimisations because the accurate version just gives very crackly sound and the RetroArch Fast Forward does nothing. Too accurate and intensive. :)

**Comment by sonninnos** [comment]
For the time being the answer is "theffuu", because nuklear gui should have absolutely zero to do with what emutype is used.

**Comment by MajorWilly** [comment]
I'm on the default 6581F and it's too demanding. I have TDE on because a lot of demos (and games) need it. If I use the Retroarch Fast Forward it's the same speed. It seems weird that the virtual keyboard works on Vice64sc but crashes on Vice64. Shame it's not the other way round. Would it be a makefile problem or Android API level not low enough (I think the Retroarch lowest is 16 but noticed 19 in the makefile).
I don't think rsn8887's commit to bypass Android optimisations has kicked in on buildbot yet so don't know if that's going to work or also slow it down.

**Comment by rsn8887** [comment]
Yes try the next buildbot version of x64 just to see. Disabling optimizations on Android  is not a permanent fix of course, but whether it crashes or not will tell us something. Once we know what is going on, I will turn the optimizations back on.

One thing that optimizations can cause problems with is variables are sometimes not automatically initialized to zero, e.g. ‘int a’ is not zero unless ‘int a = 0’ is used. It is up to the compiler really. Hopefully it is something simple like that.

**Comment by MajorWilly** [comment]
I tried the version on buildbot (3rd Aug 03.04am). I'm not completely sure if it's up to date because there is no commit version hash in RetroArch. Anyway, unfortunately the virtual keyboard still crashes RetroArch.

**Comment by rsn8887** [comment]
Well that means I should turn the optimizations back on since that is not making any difference.

**Comment by rsn8887** [comment]
Never mind I just realized in the makefile the optimizations were turned back on later. So now I actually turned them off. I will turn them on tomorrow if it still crashes then.

**Comment by MajorWilly** [comment]
I think @sonninnos pushed some keyboard fixes as well https://github.com/libretro/vice-libretro/commit/b3370df17b5990c5bfa93067f3d5886cca841f88 Will you know what commit fixes it ? (If it does !)

**Comment by rsn8887** [comment]
If anything from today fixes the crash, then I will enable optimizations again tomorrow, and see if the crash comes back :) If not, we are good.

**Comment by MajorWilly** [comment]
I just tried buildbot version '3rd Aug 15:06pm' but the keyboard still crashes. Why does the x64sc keyboard work ?

**Comment by rsn8887** [comment]
Nobody knows. It doesn't make sense really. Everything regarding on-screen virtual keyboard, retroarch etc. is exactly the same for x64sc and x64. Yet one crashes, one doesn't.

**Comment by rsn8887** [comment]
This issue should be fixed with https://github.com/libretro/vice-libretro/commit/5deed7a6648e96732d0c78bbf1c87a42b0ff4e16

Thanks to Steel01 for the help and for finding a solution!

@MajorWilly Please try the next nightly build and report if it is fixed for you.

**Comment by MajorWilly** [comment]
I haven't had much time to test today. I've just done a quick check. Thanks for adding the commit version. As of version 1e529df you'll be pleased to hear that the virtual keyboard no longer crashes !! There is some stutter when the keyboard is active but I think it did that in previous versions ?. Thanks guys, much appreciated. 

I wonder if the 'fix' would also help @DSkywalk on the Android version of libretro-cap32 ?

**Comment by rsn8887** [comment]
Good to hear it works! I will make a comment on libretro-cap32.

Yes the slowdown when keyboard is visible is normal at the moment.

I will close this.
